import { useAdminStore } from '@/stores/admin';

export type ActionLogAction = 'create' | 'update' | 'delete' | 'view' | 'navigate';

export interface ActionLogEntryInput {
  action: ActionLogAction;
  entity: string;
  entityId?: string;
  details?: string;
  status: 'success' | 'error';
}

/**
 * Generate a human-readable detail string for the given action and entity.
 */
function autoGenerateDetails(
  action: ActionLogAction,
  entity: string,
  entityId?: string
): string {
  const label = entity.replace(/([A-Z])/g, ' $1').trim();
  const idSuffix = entityId ? ` #${entityId}` : '';

  switch (action) {
    case 'create':
      return `Created new ${label}${idSuffix}`;
    case 'update':
      return `Updated ${label}${idSuffix}`;
    case 'delete':
      return `Deleted ${label}${idSuffix}`;
    case 'view':
      return `Viewed ${label}${idSuffix}`;
    case 'navigate':
      return `Navigated to ${entity}`;
    default:
      return `${action} ${label}${idSuffix}`;
  }
}

/**
 * Log an admin action to the Zustand store.
 * This is the primary entry point for recording admin activity.
 */
export function logAction(input: ActionLogEntryInput): void {
  const details = input.details || autoGenerateDetails(input.action, input.entity, input.entityId);

  const store = useAdminStore.getState();
  store.addActionLog({
    action: input.action,
    entity: input.entity,
    entityId: input.entityId,
    details,
    status: input.status,
  });
}
